# Generated by Django 5.1.3 on 2024-11-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_v20state_alter_voter_v21primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='year_of_birth',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='dob',
            field=models.DateField(),
        ),
    ]
