# Generated by Django 5.1.3 on 2024-11-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_name_item_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
    ]
