# Generated by Django 5.1.3 on 2024-11-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_profile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image_url',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
