# Generated by Django 5.1.3 on 2024-12-05 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_profile_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='project.profile'),
        ),
    ]
