# Generated by Django 5.1.3 on 2024-12-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_item_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image_url',
            new_name='profile_picture',
        ),
    ]
