# Generated by Django 5.1.3 on 2024-12-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_item_sold_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type_of_item',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('clothing', 'Clothing'), ('books', 'Books'), ('toys', 'Toys'), ('other', 'Other')], max_length=30),
        ),
    ]
